name: common
description: "Common package for khelkood Flutter projects."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Services
  firebase_core: ^4.0.0 # Firebase core functionality
  firebase_auth: ^6.0.1 # Firebase authentication
  cloud_firestore: ^6.0.0 # Cloud Firestore database
  firebase_database: ^12.0.0 # Firebase Realtime Database
  firebase_storage: ^13.0.0 # Firebase cloud storage
  firebase_remote_config: ^6.0.0 # Firebase Remote Config
  firebase_crashlytics: ^5.0.1 # Firebase Crashlytics
  firebase_analytics: ^12.0.0 # Firebase Analytics
  firebase_app_check: ^0.4.0 # Firebase App Check
  cloud_functions: ^6.0.0 # Firebase Cloud Functions client
  
  # Utilities and Helpers
  device_info_plus: ^11.5.0
  logging: ^1.3.0
  envied: ^1.1.1
  equatable: ^2.0.7
  
  # Web
  web: ^1.1.1

  # State Management and Routing
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  go_router: ^17.0.1

  # UI Components
  hexcolor: ^3.0.1
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.1
  app_settings: ^6.1.1
  firebase_messaging: ^16.0.2
  google_sign_in: ^6.2.1

dev_dependencies:
   # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.15

  # Riverpod code generator 
  riverpod_generator: ^3.0.3

  # A code generator for envied.
  envied_generator: ^1.1.1
  
  # Testing
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
